--- #YAML:1.0
name:                Parse-Readelf
version:             0.03
abstract:            handle readelf's output with a class
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Thomas Dorner <dorner (AT) pause.org>
